// Spanish content for the six expedition dossiers. Merged over the English
// base objects when the site language is "es" — brand names (expedition
// titles) intentionally stay in English everywhere on the site.
import type { ExpeditionDetail } from "@/pages/expedition-detail";

type EsOverride = Partial<Omit<ExpeditionDetail, "id" | "videoUrl" | "imageUrl" | "galleryImages">>;

export const expeditionDetailsEs: Record<string, EsOverride> = {
  "kazakhstan-steppe": {
    tagline: "Donde el horizonte se curva hasta tocar el cielo",
    heroDescription: "Atraviesa la infinita estepa dorada a caballo con guías nómadas cuyos antepasados cabalgaron estos mismos senderos durante milenios.",
    overview: "Esta expedición te lleva al corazón de Asia Central, donde la vasta estepa kazaja se extiende hasta el horizonte en todas direcciones. Cabalgarás con descendientes de los grandes guerreros nómadas, acamparás bajo cielos cuajados de estrellas y contemplarás paisajes que no han cambiado en siglos. Del dramático cañón de Charyn a las dunas cantoras de Altyn Emel, este viaje revela el alma salvaje de Kazajistán.",
    duration: "12 días",
    season: "Mayo - Octubre",
    difficulty: "Moderada",
    category: "A caballo y naturaleza",
    groupSize: "4-8 viajeros",
    startingFrom: "Por solicitud",
    itinerary: [
      { day: 1, title: "Llegada a Almaty", description: "Bienvenido a Kazajistán. Traslado del aeropuerto a tu hotel boutique en el distrito histórico de Almaty. Sesión informativa y cena tradicional de bienvenida.", highlights: ["Traslado desde el aeropuerto", "Revisión de equipo", "Cena de bienvenida con delicias locales"], accommodation: "Hotel boutique en Almaty", meals: "Cena" },
      { day: 2, title: "De Almaty al cañón de Charyn", description: "Conduce hacia el este por el valle del río Ili hasta el espectacular cañón de Charyn. Comparado a menudo con el Gran Cañón, esta formación de 150 millones de años revela la historia de la Tierra en capas de roca roja.", highlights: ["Exploración del cañón de Charyn", "Caminata por el Valle de los Castillos", "Fotografía al atardecer"], accommodation: "Eco-lodge junto al cañón", meals: "Desayuno, almuerzo, cena" },
      { day: 3, title: "Hacia la estepa", description: "Conoce a tus guías nómadas y sus caballos al borde de la estepa. Comienza el viaje hacia los pastizales infinitos, aprendiendo técnicas de monta transmitidas de generación en generación.", highlights: ["Ceremonia de elección del caballo", "Primera cabalgata en la estepa", "Campamento tradicional de yurtas"], accommodation: "Campamento tradicional de yurtas", meals: "Desayuno, almuerzo, cena" },
      { day: 4, title: "Los pastizales dorados", description: "Un día entero cabalgando por la estepa, siguiendo antiguas rutas de migración usadas por los nómadas durante milenios. Tus guías comparten historias de sus antepasados y de los espíritus que habitan estas tierras.", highlights: ["Jornada completa a caballo", "Historias y leyendas nómadas", "Degustación de kumis (leche de yegua fermentada)"], accommodation: "Campamento móvil de yurtas", meals: "Desayuno, almuerzo, cena" },
      { day: 5, title: "El valle del cazador de águilas", description: "Cabalga hasta un valle remoto donde un maestro berkutchi (cazador con águilas) demuestra esta antigua tradición. Observa a las águilas reales elevarse y volver al guante de su cuidador.", highlights: ["Demostración de caza con águilas", "Encuentro con la familia berkutchi", "Taller de artesanía tradicional"], accommodation: "Yurta de huéspedes con familia local", meals: "Desayuno, almuerzo, cena" },
      { day: 6, title: "Las dunas cantoras", description: "Viaje al Parque Nacional Altyn Emel y su famosa Duna Cantora. Esta media luna de arena de 150 metros produce un zumbido sobrenatural cuando el viento pasa sobre su superficie.", highlights: ["Ascenso a la Duna Cantora", "Avistamiento de fauna del desierto", "Atardecer sobre las dunas"], accommodation: "Campamento en el desierto", meals: "Desayuno, almuerzo, cena" },
      { day: 7, title: "Petroglifos milenarios", description: "Explora Tamgaly, Patrimonio de la Humanidad con más de 5.000 grabados rupestres de la Edad del Bronce. Estas imágenes sagradas abren una ventana al mundo espiritual de los antiguos pueblos de la estepa.", highlights: ["Recorrido por los petroglifos de Tamgaly", "Guía experto en arqueología", "Sitios rituales sagrados"], accommodation: "Casa de huéspedes cerca de Tamgaly", meals: "Desayuno, almuerzo, cena" },
      { day: 8, title: "Lagos Kolsai", description: "Viaje a los impresionantes lagos Kolsai, conocidos como las 'Perlas del Tien Shan'. Camina entre bosques alpinos hasta el primer y segundo lago, cuyas aguas turquesa reflejan picos nevados.", highlights: ["Caminata entre lagos", "Pícnic en pradera alpina", "Observación de fauna"], accommodation: "Refugio de montaña", meals: "Desayuno, almuerzo, cena" },
      { day: 9, title: "Lago Kaindy", description: "Visita el misterioso lago Kaindy, donde un bosque sumergido de abetos se alza como centinelas en el agua esmeralda. Este paisaje surrealista nació de un terremoto hace más de un siglo.", highlights: ["Exploración del lago Kaindy", "Bosque sumergido", "Sesión fotográfica"], accommodation: "Refugio de montaña", meals: "Desayuno, almuerzo, cena" },
      { day: 10, title: "Regreso a la estepa", description: "Última cabalgata por la estepa con tus compañeros nómadas. Una ceremonia de despedida bajo el cielo inmenso celebra los lazos formados durante el viaje.", highlights: ["Cabalgata final", "Ceremonia de despedida", "Música y danza tradicional"], accommodation: "Campamento de yurtas", meals: "Desayuno, almuerzo, cena" },
      { day: 11, title: "Regreso a Almaty", description: "Vuelta a Almaty con una comprensión más profunda de la vida nómada. Tarde libre para explorar el Bazar Verde y los cafés modernos. Cena de despedida en un reconocido restaurante local.", highlights: ["Visita al Bazar Verde", "Exploración de la ciudad", "Cena de despedida"], accommodation: "Hotel boutique en Almaty", meals: "Desayuno, cena" },
      { day: 12, title: "Partida", description: "Traslado al aeropuerto para tu vuelo. Partes con recuerdos de horizontes infinitos, tradiciones milenarias y el espíritu de la estepa.", highlights: ["Traslado al aeropuerto", "Asistencia en la salida"], accommodation: "N/A", meals: "Desayuno" },
    ],
    included: ["Todo el alojamiento descrito", "Todas las comidas indicadas en el itinerario", "Guías locales expertos y traductores", "Todo el transporte terrestre", "Caballo y equipo para los días de monta", "Entradas a parques nacionales", "Experiencias y demostraciones culturales", "Comunicación satelital de emergencia", "Asistencia integral con el seguro de viaje"],
    notIncluded: ["Vuelos internacionales", "Visado de Kazajistán (si aplica)", "Seguro de viaje personal", "Bebidas alcohólicas", "Gastos personales y propinas", "Actividades opcionales fuera del itinerario"],
    highlights: ["Cabalga con auténticos guías nómadas", "Presencia la caza con águilas", "Acampa en yurtas tradicionales", "Explora el cañón de Charyn", "Sube a las Dunas Cantoras", "Camina hasta lagos alpinos esmeralda"],
  },
  "kyrgyzstan-heights": {
    tagline: "Duerme donde anidan las águilas",
    heroDescription: "Recorre las montañas Tien Shan hasta el lago Son-Kul, donde los pastos de verano se convierten en espejos que reflejan un cielo infinito.",
    overview: "Las Montañas Celestiales de Kirguistán ofrecen algunos de los paisajes más dramáticos de Asia Central. Esta expedición te lleva al corazón del Tien Shan: convivirás con pastores seminómadas en el lago Son-Kul, aprenderás la caza con águilas de maestros berkutchis y caminarás por altos valles alpinos. Es un viaje a una forma de vida que ha sobrevivido intacta durante siglos.",
    duration: "10 días",
    season: "Junio - Septiembre",
    difficulty: "Exigente",
    category: "Trekking y cultura",
    groupSize: "4-6 viajeros",
    startingFrom: "Por solicitud",
    itinerary: [
      { day: 1, title: "Llegada a Bishkek", description: "Bienvenido a Kirguistán. Traslado a tu hotel y orientación vespertina. Paseo por los bulevares arbolados antes de una cena tradicional kirguisa.", highlights: ["Recogida en el aeropuerto", "Paseo de orientación", "Cena de bienvenida"], accommodation: "Hotel en Bishkek", meals: "Cena" },
      { day: 2, title: "De Bishkek a Kochkor", description: "Conduce hacia el sur por el espectacular desfiladero de Boom hasta la aldea de Kochkor. Visita una cooperativa de mujeres artesanas del fieltro y descubre el antiguo arte del shyrdak.", highlights: ["Desfiladero de Boom", "Taller de fieltro", "Cena con familia local"], accommodation: "Casa de huéspedes en Kochkor", meals: "Desayuno, almuerzo, cena" },
      { day: 3, title: "Trekking al lago Son-Kul", description: "Comienza la caminata hacia Son-Kul, uno de los lagos alpinos más grandes del mundo. Cruza pasos de montaña con vistas panorámicas del Tien Shan antes de descender al lago.", highlights: ["Trekking de montaña", "Paso a 3.400 m", "Primeras vistas de Son-Kul"], accommodation: "Yurta de pastores en Son-Kul", meals: "Desayuno, almuerzo, cena" },
      { day: 4, title: "La vida en Son-Kul", description: "Un día con los pastores de Son-Kul. Participa en sus tareas, aprende a preparar leche de yegua fermentada y cabalga por los pastos de verano. La superficie del lago refleja el cielo infinito.", highlights: ["Vida cotidiana del pastor", "Paseo a caballo", "Preparación de comida tradicional"], accommodation: "Yurta de pastores en Son-Kul", meals: "Desayuno, almuerzo, cena" },
      { day: 5, title: "Al valle de Naryn", description: "Desciende desde Son-Kul entre praderas floridas hasta el valle de Naryn. Traslado a la ciudad de Naryn, puerta de las altas montañas.", highlights: ["Descenso a pie", "Flora de pradera alpina", "Exploración de Naryn"], accommodation: "Casa de huéspedes en Naryn", meals: "Desayuno, almuerzo, cena" },
      { day: 6, title: "La aldea del cazador de águilas", description: "Viaja a una aldea remota donde un maestro cazador enseña su arte milenario. Dedica el día a comprender el vínculo entre cazador y águila.", highlights: ["Demostración de caza con águilas", "Técnicas de adiestramiento", "Historia de la caza"], accommodation: "Casa del cazador de águilas", meals: "Desayuno, almuerzo, cena" },
      { day: 7, title: "Caravasar de Tash Rabat", description: "Conduce hasta Tash Rabat, un misterioso caravasar de piedra del siglo XV en la antigua Ruta de la Seda. Explora sus cámaras oscuras y acampa cerca.", highlights: ["Historia de la Ruta de la Seda", "Exploración del caravasar", "Observación de estrellas"], accommodation: "Campamento de yurtas en Tash Rabat", meals: "Desayuno, almuerzo, cena" },
      { day: 8, title: "Trekking por pastos de altura", description: "Camina hasta remotos pastos de verano donde los pastores llevan sus rebaños. Adéntrate en valles rara vez visitados, con vistas hacia la frontera china.", highlights: ["Valles remotos", "Encuentros con pastores", "Fotografía de montaña"], accommodation: "Acampada libre", meals: "Desayuno, almuerzo, cena" },
      { day: 9, title: "Regreso a Bishkek", description: "Vuelta a Bishkek entre paisajes cambiantes. Parada en la torre de Burana, vestigio de una antigua ciudad de la Ruta de la Seda. Cena de despedida.", highlights: ["Torre de Burana", "Ruta panorámica", "Cena de despedida"], accommodation: "Hotel en Bishkek", meals: "Desayuno, cena" },
      { day: 10, title: "Partida", description: "Traslado al aeropuerto para tu vuelo. Llévate contigo el espíritu de las montañas celestiales y de su gente resiliente.", highlights: ["Traslado al aeropuerto"], accommodation: "N/A", meals: "Desayuno" },
    ],
    included: ["Todo el alojamiento descrito", "Todas las comidas indicadas", "Guías de montaña experimentados", "Todo el transporte terrestre", "Caballos para los días de monta", "Equipo de acampada", "Experiencias culturales", "Apoyo de emergencia"],
    notIncluded: ["Vuelos internacionales", "Seguro de viaje personal", "Tasas de visado", "Bebidas alcohólicas", "Gastos personales", "Propinas para guías"],
    highlights: ["Trekking al lago alpino Son-Kul", "Convive con pastores nómadas", "Aprende la caza con águilas", "Explora un caravasar de la Ruta de la Seda", "Cruza altos pasos de montaña", "Vive la auténtica vida en yurta"],
  },
  "mongolia-gobi": {
    tagline: "Donde el silencio se convierte en el sonido más fuerte",
    heroDescription: "Adéntrate en el desierto de Gobi con caravanas de camellos y familias nómadas.",
    overview: "El Gobi no es solo un paisaje: es un estado mental. Esta expedición te lleva a una de las últimas grandes tierras salvajes del planeta, viajando con caravanas de camellos y conviviendo con familias nómadas en sus gers tradicionales. De los Acantilados Llameantes a las arenas cantoras de Khongoryn Els, vivirás Mongolia en su versión más cruda y reveladora.",
    duration: "14 días",
    season: "Abril - Octubre",
    difficulty: "Moderada",
    category: "Desierto y vida nómada",
    groupSize: "4-8 viajeros",
    startingFrom: "Por solicitud",
    itinerary: [
      { day: 1, title: "Llegada a Ulán Bator", description: "Bienvenido a Mongolia. Traslado al hotel y sesión informativa sobre el viaje que comienza.", highlights: ["Traslado desde el aeropuerto", "Revisión de equipo", "Cena de bienvenida"], accommodation: "Hotel en Ulán Bator", meals: "Cena" },
      { day: 2, title: "Vuelo al Gobi", description: "Vuelo matinal a Dalanzadgad, puerta del Gobi. Conduce hacia el desierto hasta tu primer campamento de gers.", highlights: ["Vuelo panorámico", "Primeras vistas del Gobi", "Orientación en el campamento"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 3, title: "Valle de Yol", description: "Explora el dramático valle de Yol, una garganta estrecha donde el hielo persiste incluso en verano. Busca argalíes y quebrantahuesos.", highlights: ["Caminata por el valle de Yol", "Avistamiento de fauna", "Garganta de hielo"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 4, title: "Khongoryn Els", description: "Viaje a las arenas cantoras de Khongoryn Els, algunas de las dunas más grandes de Mongolia.", highlights: ["Exploración de dunas", "Ascenso al atardecer", "Observación de estrellas"], accommodation: "Campamento junto a las dunas", meals: "Desayuno, almuerzo, cena" },
      { day: 5, title: "Caravana de camellos", description: "Únete a una caravana tradicional para atravesar el desierto. Tus camellos bactrianos llevan las provisiones mientras caminas a su lado.", highlights: ["Manejo de camellos", "Travesía del desierto", "Historias nómadas"], accommodation: "Campamento móvil", meals: "Desayuno, almuerzo, cena" },
      { day: 6, title: "Familia nómada", description: "Convive con una familia de pastores nómadas. Participa en sus tareas diarias y descubre cómo es la vida en el Gobi.", highlights: ["Vida cotidiana del pastor", "Demostración de ordeño", "Cocina tradicional"], accommodation: "Ger familiar", meals: "Desayuno, almuerzo, cena" },
      { day: 7, title: "Acantilados Llameantes", description: "Visita Bayanzag, los Acantilados Llameantes donde Roy Chapman Andrews descubrió huevos de dinosaurio en los años veinte.", highlights: ["Yacimiento paleontológico", "Colores del atardecer", "Búsqueda de fósiles"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 8, title: "La Estupa Blanca", description: "Explora las formaciones rocosas de la Estupa Blanca y busca al esquivo oso del Gobi.", highlights: ["Formaciones rocosas", "Búsqueda de fauna", "Fotografía"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 9, title: "Monasterio de Ongi", description: "Conduce hasta las ruinas del monasterio de Ongi, en su día uno de los mayores centros budistas de Mongolia.", highlights: ["Ruinas del monasterio", "Historia budista", "Valle del río"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 10, title: "Estepas centrales", description: "Deja atrás el Gobi y entra en las estepas centrales. Visita familias nómadas por el camino.", highlights: ["Transición de paisajes", "Visitas a nómadas", "Paseo a caballo"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 11, title: "Karakórum", description: "Visita Karakórum, la antigua capital del imperio de Gengis Kan, y el monasterio Erdene Zuu.", highlights: ["Historia del Imperio mongol", "Recorrido por el monasterio", "Visita al museo"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 12, title: "Valle del Orjón", description: "Explora el valle del Orjón, Patrimonio de la Humanidad de extraordinaria belleza natural.", highlights: ["Cascada del Orjón", "Caminata por el valle", "Aguas termales"], accommodation: "Campamento de gers", meals: "Desayuno, almuerzo, cena" },
      { day: 13, title: "Regreso a Ulán Bator", description: "Vuelta a la capital entre colinas onduladas. Cena de despedida para celebrar tu travesía del Gobi.", highlights: ["Ruta panorámica", "Llegada a la ciudad", "Cena de despedida"], accommodation: "Hotel en Ulán Bator", meals: "Desayuno, cena" },
      { day: 14, title: "Partida", description: "Traslado al aeropuerto. Partes con el silencio del Gobi grabado en la memoria.", highlights: ["Traslado al aeropuerto"], accommodation: "N/A", meals: "Desayuno" },
    ],
    included: ["Todo el alojamiento", "Todas las comidas indicadas", "Vuelo doméstico", "Vehículos 4x4", "Camellos para la caravana", "Guías expertos", "Entradas a parques nacionales", "Apoyo de emergencia"],
    notIncluded: ["Vuelos internacionales", "Seguro de viaje", "Visado", "Bebidas alcohólicas", "Gastos personales", "Propinas"],
    highlights: ["Cruza el Gobi en caravana de camellos", "Convive con familias nómadas", "Sube dunas de arenas cantoras", "Visita yacimientos de dinosaurios", "Duerme en gers tradicionales", "Explora la antigua Karakórum"],
  },
  "nepal-mustang": {
    tagline: "Más allá del velo del Himalaya",
    heroDescription: "Entra en el Alto Mustang, el último reino prohibido, donde la cultura tibetana pervive en monasterios milenarios y ciudades excavadas en la roca.",
    overview: "Hasta 1992, el Alto Mustang estuvo cerrado al mundo exterior. Esta expedición te adentra en este remoto reino himalayo, caminando por paisajes lunares de rojos y ocres hasta la antigua ciudad amurallada de Lo Manthang. Explorarás monasterios rupestres decorados con pinturas centenarias, dormirás en casas tibetanas tradicionales y serás testigo de una cultura que apenas ha cambiado desde la Edad Media.",
    duration: "16 días",
    season: "Marzo - Noviembre",
    difficulty: "Exigente",
    category: "Trekking y lugares sagrados",
    groupSize: "4-8 viajeros",
    startingFrom: "Por solicitud",
    itinerary: [
      { day: 1, title: "Llegada a Katmandú", description: "Bienvenido a Nepal. Traslado a tu hotel con encanto en la ciudad vieja. Sesión informativa y cena de bienvenida.", highlights: ["Traslado desde el aeropuerto", "Hotel con historia", "Cena de bienvenida"], accommodation: "Hotel con encanto", meals: "Cena" },
      { day: 2, title: "Exploración de Katmandú", description: "Visita los lugares sagrados del valle de Katmandú: Boudhanath, Pashupatinath y la plaza Durbar de Patan.", highlights: ["Estupa de Boudhanath", "Templo de Pashupatinath", "Plaza Durbar de Patan"], accommodation: "Hotel con encanto", meals: "Desayuno" },
      { day: 3, title: "Vuelo a Pokhara", description: "Vuelo matinal a Pokhara con vistas de la cordillera del Himalaya. Tarde libre para explorar esta ciudad junto al lago.", highlights: ["Vuelo sobre el Himalaya", "Lago Phewa", "Exploración libre"], accommodation: "Hotel junto al lago", meals: "Desayuno" },
      { day: 4, title: "Vuelo a Jomsom", description: "Espectacular vuelo de montaña a Jomsom. Comienza el trekking hacia Kagbeni, puerta del Alto Mustang.", highlights: ["Vuelo de montaña", "Inicio del trekking", "Llegada a Kagbeni"], accommodation: "Albergue en Kagbeni", meals: "Desayuno, almuerzo, cena" },
      { day: 5, title: "De Kagbeni a Chele", description: "Entra en la zona restringida del Alto Mustang. Camina junto a la garganta del Kali Gandaki hasta Chele.", highlights: ["Control de permisos", "Trekking por la garganta", "Aldeas de acantilados rojos"], accommodation: "Albergue en Chele", meals: "Desayuno, almuerzo, cena" },
      { day: 6, title: "De Chele a Syangboche", description: "Cruza dos pasos de altura con vistas imponentes. Desciende hasta la aldea de Syangboche.", highlights: ["Cruce de pasos", "Vistas panorámicas", "Aldea tradicional"], accommodation: "Albergue en Syangboche", meals: "Desayuno, almuerzo, cena" },
      { day: 7, title: "De Syangboche a Ghami", description: "Camina entre cañones erosionados y paisajes lunares hasta Ghami, la segunda población del Alto Mustang.", highlights: ["Paisajes de cañón", "Muros mani", "Exploración de Ghami"], accommodation: "Albergue en Ghami", meals: "Desayuno, almuerzo, cena" },
      { day: 8, title: "De Ghami a Tsarang", description: "Visita el antiguo monasterio de Ghami antes de continuar hasta Tsarang y su imponente fortaleza dzong.", highlights: ["Monasterio de Ghami", "Dzong de Tsarang", "Viviendas rupestres"], accommodation: "Albergue en Tsarang", meals: "Desayuno, almuerzo, cena" },
      { day: 9, title: "De Tsarang a Lo Manthang", description: "Cruza el último paso hasta la ciudad amurallada de Lo Manthang, capital del antiguo Reino de Lo.", highlights: ["Paso de altura", "Primera vista de Lo", "Entrada a la ciudad amurallada"], accommodation: "Casa tradicional en Lo Manthang", meals: "Desayuno, almuerzo, cena" },
      { day: 10, title: "Lo Manthang", description: "Día completo explorando Lo Manthang: el palacio real, los monasterios antiguos y las cuevas sagradas.", highlights: ["Palacio real", "Thubchen Gompa", "Champa Lakhang"], accommodation: "Casa tradicional en Lo Manthang", meals: "Desayuno, almuerzo, cena" },
      { day: 11, title: "Monasterios rupestres", description: "Excursión a las cuevas de Choser, excavadas en el acantilado y decoradas con pinturas budistas milenarias.", highlights: ["Cueva de Jhong", "Pinturas antiguas", "Cuevas con tragaluz"], accommodation: "Casa tradicional en Lo Manthang", meals: "Desayuno, almuerzo, cena" },
      { day: 12, title: "Comienza el regreso", description: "Despídete de Lo Manthang y emprende el regreso por una ruta alternativa.", highlights: ["Ruta alternativa", "Nuevas perspectivas", "Ghar Gompa"], accommodation: "Albergue en Drakmar", meals: "Desayuno, almuerzo, cena" },
      { day: 13, title: "De Drakmar a Samar", description: "Camina entre los acantilados rojos de Drakmar hasta la aldea de Samar.", highlights: ["Acantilados rojos", "Cuevas de meditación", "Vida de aldea"], accommodation: "Albergue en Samar", meals: "Desayuno, almuerzo, cena" },
      { day: 14, title: "De Samar a Jomsom", description: "Completa el trekking de vuelta a Jomsom por la garganta del Kali Gandaki.", highlights: ["Vistas de la garganta", "Fin del trekking", "Cena de celebración"], accommodation: "Albergue en Jomsom", meals: "Desayuno, almuerzo, cena" },
      { day: 15, title: "Regreso a Katmandú", description: "Vuela de Jomsom a Pokhara y conecta con Katmandú. Cena de despedida en la ciudad vieja.", highlights: ["Vuelos de montaña", "Regreso a la ciudad", "Cena de despedida"], accommodation: "Hotel con encanto", meals: "Desayuno, cena" },
      { day: 16, title: "Partida", description: "Traslado al aeropuerto para tu vuelo. Llévate contigo el espíritu del reino prohibido.", highlights: ["Traslado al aeropuerto"], accommodation: "N/A", meals: "Desayuno" },
    ],
    included: ["Todo el alojamiento", "Todas las comidas indicadas", "Vuelos domésticos", "Permiso del Alto Mustang", "Tarjeta TIMS", "Guías expertos y porteadores", "Seguro de evacuación de emergencia"],
    notIncluded: ["Vuelos internacionales", "Visado de Nepal", "Seguro de viaje personal", "Bebidas alcohólicas", "Gastos personales", "Propinas"],
    highlights: ["Trekking a la ciudad amurallada de Lo Manthang", "Explora monasterios rupestres", "Cultura tibetana preservada", "Cruza altos pasos del Himalaya", "Duerme en casas tradicionales", "Paisajes lunares"],
  },
  "bhutan-sacred": {
    tagline: "Donde la felicidad se mide de otra manera",
    heroDescription: "Recorre los senderos sagrados del Reino del Dragón del Trueno con monjes y guías locales.",
    overview: "Bután sigue siendo uno de los reinos más misteriosos e intactos del mundo. Esta expedición combina caminatas sagradas con una inmersión cultural profunda: del icónico Nido del Tigre a monasterios remotos donde el silencio se guarda desde hace siglos. Caminarás entre bosques de rododendros, asistirás a enseñanzas con lamas budistas y conocerás una tierra donde la espiritualidad impregna cada valle.",
    duration: "11 días",
    season: "Marzo - Mayo, Sept - Nov",
    difficulty: "Moderada",
    category: "Sagrado y espiritual",
    groupSize: "4-8 viajeros",
    startingFrom: "Por solicitud",
    itinerary: [
      { day: 1, title: "Llegada a Paro", description: "Vuela a Paro entre los picos del Himalaya. Traslado a tu resort junto al río. Ceremonia de bendición al atardecer.", highlights: ["Vuelo sobre el Himalaya", "Vistas del valle de Paro", "Ceremonia de bendición"], accommodation: "Resort junto al río", meals: "Cena" },
      { day: 2, title: "El Nido del Tigre", description: "Sube a Paro Taktsang, el sagrado monasterio del Nido del Tigre, suspendido en un acantilado de 900 metros.", highlights: ["Ascenso al Nido del Tigre", "Visita al monasterio", "Meditación en el acantilado"], accommodation: "Resort junto al río", meals: "Desayuno, almuerzo, cena" },
      { day: 3, title: "De Paro a Thimphu", description: "Conduce hasta Thimphu, la única capital del mundo sin semáforos. Visita el Memorial Chorten y el Buda Dordenma.", highlights: ["Exploración de la capital", "Buda gigante", "Papel artesanal tradicional"], accommodation: "Hotel en Thimphu", meals: "Desayuno, almuerzo, cena" },
      { day: 4, title: "Thimphu a fondo", description: "Día completo en Thimphu. Visita el museo del patrimonio, el museo textil y participa en una partida de tiro con arco.", highlights: ["Museos", "Tiro con arco", "Oraciones vespertinas"], accommodation: "Hotel en Thimphu", meals: "Desayuno, almuerzo, cena" },
      { day: 5, title: "Paso de Dochula", description: "Cruza el paso de Dochula con vistas de la cordillera del Himalaya. Visita los 108 chortens y continúa hasta Punakha.", highlights: ["108 chortens", "Panorámica del Himalaya", "Valle de Punakha"], accommodation: "Resort en Punakha", meals: "Desayuno, almuerzo, cena" },
      { day: 6, title: "Dzong de Punakha", description: "Explora el dzong de Punakha, quizá la fortaleza-monasterio más bella de Bután. Camina hasta Chimi Lhakhang, el templo de la fertilidad.", highlights: ["Dzong de Punakha", "Caminata a Chimi Lhakhang", "Paseo entre arrozales"], accommodation: "Resort en Punakha", meals: "Desayuno, almuerzo, cena" },
      { day: 7, title: "Caminata a Khamsum", description: "Caminata de un día entre aldeas y bosque hasta Khamsum Yulley Namgyal Chorten, un impresionante templo en lo alto de una colina.", highlights: ["Trekking entre aldeas", "Visita al templo", "Vistas del valle"], accommodation: "Resort en Punakha", meals: "Desayuno, almuerzo, cena" },
      { day: 8, title: "Valle de Gangtey", description: "Conduce hasta Gangtey, hogar invernal de las grullas cuellinegras. Alójate en una granja tradicional.", highlights: ["Valle de Phobjikha", "Gangtey Gompa", "Estancia en granja"], accommodation: "Granja en Gangtey", meals: "Desayuno, almuerzo, cena" },
      { day: 9, title: "Senderos de Gangtey", description: "Explora los senderos naturales del valle. Visita el centro de grullas y disfruta de un pícnic en las praderas.", highlights: ["Senderos naturales", "Centro de grullas", "Meditación en el valle"], accommodation: "Granja en Gangtey", meals: "Desayuno, almuerzo, cena" },
      { day: 10, title: "Regreso a Paro", description: "Vuelta a Paro. Baño tradicional de piedras calientes y cena de despedida para celebrar el viaje.", highlights: ["Ruta panorámica", "Baño de piedras calientes", "Cena de despedida"], accommodation: "Resort junto al río", meals: "Desayuno, cena" },
      { day: 11, title: "Partida", description: "Mañana libre antes de tu vuelo entre las montañas del Himalaya. Llévate contigo las bendiciones del Dragón del Trueno.", highlights: ["Últimas vistas", "Vuelo de salida"], accommodation: "N/A", meals: "Desayuno" },
    ],
    included: ["Todo el alojamiento", "Todas las comidas indicadas", "Tasa de Desarrollo Sostenible", "Guías expertos", "Todo el transporte terrestre", "Entradas a monumentos", "Experiencias culturales"],
    notIncluded: ["Vuelos internacionales", "Tasa de visado de Bután", "Seguro de viaje personal", "Bebidas alcohólicas", "Gastos personales", "Propinas"],
    highlights: ["Sube al monasterio del Nido del Tigre", "Explora antiguas fortalezas dzong", "Cruza altos pasos de montaña", "Alójate en una granja tradicional", "Presencia ceremonias budistas", "Descubre la Felicidad Nacional Bruta"],
  },
  "indonesia-flores": {
    tagline: "Donde la tierra aún respira",
    heroDescription: "Navega por el archipiélago indonesio de Flores a Komodo, buceando arrecifes volcánicos y caminando entre dragones.",
    overview: "Esta expedición marítima te lleva por el corazón volcánico del archipiélago indonesio. De los lagos tricolores del Kelimutu a los dragones de Komodo, de arrecifes de coral vírgenes a aldeas ancestrales en Sumba: esta es la Indonesia más salvaje e intacta. Viajarás en un velero tradicional de madera, acamparás en islas deshabitadas y sentirás la fuerza bruta del Anillo de Fuego.",
    duration: "13 días",
    season: "Abril - Noviembre",
    difficulty: "Moderada",
    category: "Marina y volcánica",
    groupSize: "6-10 viajeros",
    startingFrom: "Por solicitud",
    itinerary: [
      { day: 1, title: "Llegada a Labuan Bajo", description: "Vuela a Flores y traslada a tu hotel frente al mar. Copas al atardecer con vistas a la bahía.", highlights: ["Llegada a Flores", "Vistas del puerto", "Cena de bienvenida"], accommodation: "Hotel frente al mar", meals: "Cena" },
      { day: 2, title: "Dragones de Komodo", description: "Navega al Parque Nacional de Komodo. Recorre la isla en busca de dragones de Komodo en su hábitat natural.", highlights: ["Trekking entre dragones", "Observación de fauna", "Recorrido con guardas"], accommodation: "Velero tradicional", meals: "Desayuno, almuerzo, cena" },
      { day: 3, title: "Isla de Rinca", description: "Visita Rinca para más encuentros con dragones. Por la tarde, esnórquel en arrecifes vírgenes.", highlights: ["Dragones de Rinca", "Esnórquel en coral", "Exploración de la isla"], accommodation: "Velero tradicional", meals: "Desayuno, almuerzo, cena" },
      { day: 4, title: "Playa Rosa", description: "Pasa el día en Pink Beach, una de las siete playas de arena rosa del mundo. Esnórquel entre jardines de coral vibrantes.", highlights: ["Arena rosa", "Esnórquel en coral", "Descanso en la playa"], accommodation: "Velero tradicional", meals: "Desayuno, almuerzo, cena" },
      { day: 5, title: "Manta Point", description: "Inmersión al amanecer con mantarrayas en el famoso Manta Point. Por la tarde, rumbo a islas remotas.", highlights: ["Encuentro con mantas", "Buceo y esnórquel", "Islas remotas"], accommodation: "Velero tradicional", meals: "Desayuno, almuerzo, cena" },
      { day: 6, title: "Regreso a Flores", description: "Navega de vuelta a Flores. Sube a las tierras altas hasta la aldea tradicional de Bena.", highlights: ["Ruta de montaña", "Aldea de Bena", "Casas tradicionales"], accommodation: "Casa de huéspedes en Bajawa", meals: "Desayuno, almuerzo, cena" },
      { day: 7, title: "Lagos del Kelimutu", description: "Conduce al volcán Kelimutu. Caminata antes del alba para ver amanecer sobre los tres lagos de colores.", highlights: ["Caminata al alba", "Lagos tricolores", "Paisaje volcánico"], accommodation: "Eco-lodge en Kelimutu", meals: "Desayuno, almuerzo, cena" },
      { day: 8, title: "Aldeas tradicionales", description: "Explora las aldeas tradicionales ngada, con estructuras megalíticas y santuarios ancestrales.", highlights: ["Visitas a aldeas", "Inmersión cultural", "Artesanía local"], accommodation: "Casa de huéspedes", meals: "Desayuno, almuerzo, cena" },
      { day: 9, title: "Vuelo a Sumba", description: "Vuela a Sumba, la isla salvaje de Indonesia. Visita la aldea de Ratenggaro, en lo alto de una colina.", highlights: ["Llegada a Sumba", "Aldea de Ratenggaro", "Tumbas megalíticas"], accommodation: "Resort de playa", meals: "Desayuno, almuerzo, cena" },
      { day: 10, title: "Sumba a fondo", description: "Día completo explorando las aldeas tradicionales de Sumba, los centros de tejido ikat y sus playas impresionantes.", highlights: ["Tejido ikat", "Cultura de aldea", "Tiempo de playa"], accommodation: "Resort de playa", meals: "Desayuno, almuerzo, cena" },
      { day: 11, title: "Laguna Weekuri", description: "Visita las aguas turquesa de la laguna Weekuri y explora más aldeas remotas.", highlights: ["Baño en Weekuri", "Aldeas remotas", "Encuentros culturales"], accommodation: "Resort de playa", meals: "Desayuno, almuerzo, cena" },
      { day: 12, title: "Regreso a Flores", description: "Vuelo de regreso a Flores. Cena de despedida con vistas a la bahía mientras el sol se pone sobre las islas de Komodo.", highlights: ["Vuelo de regreso", "Tiempo libre", "Cena de despedida"], accommodation: "Hotel frente al mar", meals: "Desayuno, cena" },
      { day: 13, title: "Partida", description: "Traslado al aeropuerto para tu vuelo. Llévate contigo el fuego del archipiélago.", highlights: ["Traslado al aeropuerto"], accommodation: "N/A", meals: "Desayuno" },
    ],
    included: ["Todo el alojamiento", "Todas las comidas indicadas", "Velero tradicional", "Vuelos domésticos", "Entradas al parque de Komodo", "Equipo de esnórquel", "Guías expertos", "Todo el transporte terrestre"],
    notIncluded: ["Vuelos internacionales", "Seguro de viaje", "Visado", "Buceo con botella (disponible)", "Bebidas alcohólicas", "Gastos personales", "Propinas"],
    highlights: ["Camina entre dragones de Komodo", "Bucea con mantarrayas", "Amanece en el Kelimutu", "Navega en velero tradicional", "Explora aldeas ancestrales", "Descubre playas de arena rosa"],
  },
};
